version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  webhooks:
    lang: golang-middleware
    handler: ./webhooks
    image: webhooks:latest
    environment:
      GITHUB_TOKEN: foobar
      read_timeout: 30s
      write_timeout: 30s
      hard_timeout: 20s
      upstream_timeout: 20s
      write_debug: true
      exec_timeout: 0
      max_inflight: false
    build_args:
      GO111MODULE: on
